SELECT MAX(T2.NU_COBR), MAX(T1.CO_TIEN), MAX(T4.DE_TIEN), MAX(T1.TI_DOCU), MAX(T1.NU_DOCU), MAX(T1.CO_CLIE), MAX(T1.NO_CLIE), MAX(T1.DE_DIRE), MAX(T1.FE_DOCU), MAX(T1.HO_CREA),MAX(T1.CO_MONE),
CASE WHEN MAX(T1.CO_MONE) = 'DOL' 
THEN ROUND(DBO.FU_TIPO_CAMB_Q01(MAX(T1.CO_MONE),'SOL','V','M',MAX(T1.FE_DOCU),MAX(T1.IM_TOTA)),4)
ELSE MAX(T1.IM_TOTA) END AS IM_TOTA,ROUND(SUM(T2.IM_COBR),2), ISNULL(ROUND(MAX(T2.IM_COBR)/1.18,2),0) AS IM_COBR_SIGV,
MAX(T1.CO_VEND),MAX(T6.NO_VEND) + ' ' + MAX(T6.AP_PATE_VEND)+' '+MAX(T6.AP_MATE_VEND) AS NO_VEND,
SUM(PATINDEX('MER',X3.TI_ITEM)*PATINDEX('NAC',X3.TI_NACI_IMPO)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_NACI,
SUM(PATINDEX('MER',X3.TI_ITEM)*PATINDEX('IMP',X3.TI_NACI_IMPO)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_IMPO,
SUM(PATINDEX('SER',X3.TI_ITEM)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_SERV

FROM TCDOCU_CLIE T1
JOIN TDCOBR_DOCU T2
ON T1.CO_EMPR = T2.CO_EMPR
AND T1.CO_UNID = T2.CO_UNID
AND T1.CO_TIEN = T2.CO_TIEN
AND T1.TI_DOCU = T2.TI_DOCU
AND T1.NU_DOCU = T2.NU_DOCU
JOIN TDDOCU_CLIE X2
ON T2.CO_EMPR = X2.CO_EMPR
AND T2.TI_DOCU = X2.TI_DOCU
AND T2.NU_DOCU = X2.NU_DOCU
JOIN TMITEM X3
ON X2.CO_EMPR = X3.CO_EMPR
AND X2.CO_ITEM = X3.CO_ITEM
JOIN TCCOBR T3
ON T2.CO_EMPR = T3.CO_EMPR
AND T2.CO_UNID = T3.CO_UNID
AND T2.CO_TIEN = T3.CO_TIEN
AND T2.NU_COBR = T3.NU_COBR
AND T3.TI_SITU != 'ANU'	
LEFT JOIN TMTIEN T4
ON T1.CO_EMPR = T4.CO_EMPR
AND T1.CO_TIEN = T4.CO_TIEN
LEFT JOIN TMVEND T6	
ON T1.CO_EMPR = T6.CO_EMPR
AND T1.CO_UNID = T6.CO_UNID
AND T1.CO_VEND = T6.CO_VEND

WHERE T1.CO_EMPR = '02'
AND T1.CO_UNID = '001'
AND T1.FE_DOCU >= '2016/11/10'
AND T1.FE_DOCU <= '2016/11/10'
AND T1.TI_DOCU IN ( (SELECT TI_DOCU_FACT FROM TMPARA_VENT WHERE CO_EMPR='02'),(SELECT TI_DOCU_BOLE FROM TMPARA_VENT WHERE CO_EMPR='02'), 
					(SELECT TI_DOCU_TICK FROM TMPARA_VENT WHERE CO_EMPR='02'))
--AND T1.TI_FACT IN (SELECT TI_FACT_DEFA FROM TMTIEN  WHERE T1.CO_EMPR=TMTIEN.CO_EMPR AND T1.CO_TIEN = TMTIEN.CO_TIEN)
AND T1.CO_TIEN NOT IN (SELECT CO_TIEN FROM TMTIEN WHERE CO_EMPR='02' AND ST_PROY='S')
AND T1.CO_ESTA_DOCU != 'ANU'

GROUP BY T1.NU_DOCU

UNION ALL

SELECT  '',MAX(T1.CO_TIEN), MAX(T4.DE_TIEN), MAX(T1.TI_DOCU), MAX(T1.NU_DOCU), MAX(T1.CO_CLIE), MAX(T1.NO_CLIE), MAX(T1.DE_DIRE), MAX(T1.FE_DOCU), MAX(T1.HO_CREA),MAX(T1.CO_MONE),
CASE WHEN MAX(T1.TI_DOCU) = 'NCR' THEN 
CASE
WHEN MAX(T1.CO_MONE) = 'DOL' THEN - ROUND(DBO.FU_TIPO_CAMB_Q01(MAX(T1.CO_MONE),'SOL','V','M',MAX(T1.FE_DOCU),MAX(T1.IM_TOTA)),4)
ELSE -MAX(T1.IM_TOTA) END
ELSE
CASE
WHEN MAX(T1.CO_MONE) = 'DOL' THEN ROUND(DBO.FU_TIPO_CAMB_Q01(MAX(T1.CO_MONE),'SOL','V','M',MAX(T1.FE_DOCU),MAX(T1.IM_TOTA)),4)
ELSE MAX(T1.IM_TOTA) END 
END, 
0 AS IM_COBR, 0 AS IM_COBR_SIGV, MAX(T1.CO_VEND),MAX(T6.NO_VEND) + ' ' + MAX(T6.AP_PATE_VEND)+' '+MAX(T6.AP_MATE_VEND) AS NO_VEND,
SUM(PATINDEX('MER',X3.TI_ITEM)*PATINDEX('NAC',X3.TI_NACI_IMPO)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_NACI,
SUM(PATINDEX('MER',X3.TI_ITEM)*PATINDEX('IMP',X3.TI_NACI_IMPO)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_IMPO,
SUM(PATINDEX('SER',X3.TI_ITEM)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_SERV

FROM TCDOCU_CLIE T1
JOIN TDDOCU_CLIE X2
ON T1.CO_EMPR = X2.CO_EMPR
AND T1.TI_DOCU = X2.TI_DOCU
AND T1.NU_DOCU = X2.NU_DOCU
JOIN TMITEM X3
ON X2.CO_EMPR = X3.CO_EMPR
AND X2.CO_ITEM = X3.CO_ITEM
LEFT JOIN TMTIEN T4
ON T1.CO_EMPR = T4.CO_EMPR
AND T1.CO_TIEN = T4.CO_TIEN
LEFT JOIN TMVEND T6	
ON T1.CO_EMPR = T6.CO_EMPR
AND T1.CO_UNID = T6.CO_UNID
AND T1.CO_VEND = T6.CO_VEND

WHERE T1.CO_EMPR = '02'
AND T1.CO_UNID = '001'
AND T1.TI_DOCU IN ((SELECT TI_DOCU_NCRE FROM TMPARA_VENT WHERE CO_EMPR='02'),(SELECT TI_DOCU_NDEB FROM TMPARA_VENT WHERE CO_EMPR='02'))
AND T1.FE_DOCU >= '2016/11/10'
AND T1.FE_DOCU <= '2016/11/10'
AND T1.CO_ESTA_DOCU != 'ANU'
AND T1.CO_TIEN NOT IN (SELECT CO_TIEN FROM TMTIEN WHERE CO_EMPR='02' AND ST_PROY='S')

GROUP BY T1.NU_DOCU

UNION ALL

SELECT  '',MAX(T1.CO_TIEN), MAX(T4.DE_TIEN), MAX(T1.TI_DOCU), MAX(T1.NU_DOCU), MAX(T1.CO_CLIE), MAX(T1.NO_CLIE), MAX(T1.DE_DIRE), MAX(T1.FE_DOCU), MAX(T1.HO_CREA),MAX(T1.CO_MONE),
CASE WHEN MAX(T1.CO_MONE) = 'DOL' 
THEN ROUND(DBO.FU_TIPO_CAMB_Q01(MAX(T1.CO_MONE),'SOL','V','M',MAX(T1.FE_DOCU),MAX(T1.IM_TOTA)),4)
ELSE MAX(T1.IM_TOTA) END AS IM_TOTA, 0 AS IM_COBR, 0 AS IM_COBR_SIGV, MAX(T1.CO_VEND), MAX(T6.NO_VEND) + ' ' + MAX(T6.AP_PATE_VEND)+' '+MAX(T6.AP_MATE_VEND) AS NO_VEND,
SUM(PATINDEX('MER',X3.TI_ITEM)*PATINDEX('NAC',X3.TI_NACI_IMPO)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_NACI,
SUM(PATINDEX('MER',X3.TI_ITEM)*PATINDEX('IMP',X3.TI_NACI_IMPO)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_IMPO,
SUM(PATINDEX('SER',X3.TI_ITEM)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_SERV

FROM TCDOCU_CLIE T1
JOIN TDDOCU_CLIE X2
ON T1.CO_EMPR = X2.CO_EMPR
AND T1.TI_DOCU = X2.TI_DOCU
AND T1.NU_DOCU = X2.NU_DOCU
JOIN TMITEM X3
ON X2.CO_EMPR = X3.CO_EMPR
AND X2.CO_ITEM = X3.CO_ITEM
LEFT JOIN TMTIEN T4
ON T1.CO_EMPR = T4.CO_EMPR
AND T1.CO_TIEN = T4.CO_TIEN
LEFT JOIN TMVEND T6	
ON T1.CO_EMPR = T6.CO_EMPR
AND T1.CO_UNID = T6.CO_UNID
AND T1.CO_VEND = T6.CO_VEND

WHERE T1.CO_EMPR = '02'
AND T1.CO_UNID = '001'
AND T1.NU_DOCU IN (SELECT NU_DOCU FROM TCDOCU_CLIE WHERE CO_EMPR = '02' AND NU_DOCU LIKE 'F028%' UNION ALL SELECT NU_DOCU FROM TCDOCU_CLIE WHERE CO_EMPR = '02' AND NU_DOCU LIKE 'B028%')
AND T1.FE_DOCU >= '2016/11/10'
AND T1.FE_DOCU <= '2016/11/10'
AND T1.CO_ESTA_DOCU != 'ANU'
AND T1.CO_TIEN NOT IN (SELECT CO_TIEN FROM TMTIEN WHERE CO_EMPR='02' AND ST_PROY='S')

GROUP BY T1.NU_DOCU

UNION ALL

SELECT  '',MAX(T1.CO_TIEN), MAX(T4.DE_TIEN), MAX(T1.TI_DOCU), MAX(T1.NU_DOCU), MAX(T1.CO_CLIE), MAX(T1.NO_CLIE), MAX(T1.DE_DIRE), MAX(T1.FE_DOCU), MAX(T1.HO_CREA),MAX(T1.CO_MONE),
CASE WHEN MAX(T1.CO_MONE) = 'DOL' 
THEN ROUND(DBO.FU_TIPO_CAMB_Q01(MAX(T1.CO_MONE),'SOL','V','M',MAX(T1.FE_DOCU),MAX(T1.IM_TOTA)),4) 
ELSE MAX(T1.IM_TOTA) END AS IM_TOTA, 0 AS IM_COBR, 0 AS IM_COBR_SIGV, MAX(T1.CO_VEND),MAX(T6.NO_VEND) + ' ' + MAX(T6.AP_PATE_VEND)+' '+MAX(T6.AP_MATE_VEND) AS NO_VEND,
SUM(PATINDEX('MER',X3.TI_ITEM)*PATINDEX('NAC',X3.TI_NACI_IMPO)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_NACI,
SUM(PATINDEX('MER',X3.TI_ITEM)*PATINDEX('IMP',X3.TI_NACI_IMPO)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_IMPO,
SUM(PATINDEX('SER',X3.TI_ITEM)*CONVERT(NUMERIC (18,2),ROUND(DBO.FU_TIPO_CAMB_Q01(T1.CO_MONE,'SOL','V','M',T1.FE_DOCU,X2.IM_TOTA_DETA),2)))
AS TI_ITEM_SERV

FROM TCDOCU_CLIE T1
JOIN TDDOCU_CLIE X2
ON T1.CO_EMPR = X2.CO_EMPR
AND T1.TI_DOCU = X2.TI_DOCU
AND T1.NU_DOCU = X2.NU_DOCU
JOIN TMITEM X3
ON X2.CO_EMPR = X3.CO_EMPR
AND X2.CO_ITEM = X3.CO_ITEM
LEFT JOIN TMTIEN T4
ON T1.CO_EMPR = T4.CO_EMPR
AND T1.CO_TIEN = T4.CO_TIEN
LEFT JOIN TMVEND T6	
ON T1.CO_EMPR = T6.CO_EMPR
AND T1.CO_UNID = T6.CO_UNID
AND T1.CO_VEND = T6.CO_VEND

WHERE T1.CO_EMPR = '02'
AND T1.CO_UNID = '001'
AND T1.NU_COBR IS NULL
AND T1.NU_DOCU NOT IN (SELECT NU_DOCU FROM TCDOCU_CLIE WHERE CO_EMPR = '02' AND NU_DOCU LIKE 'F028%' UNION ALL SELECT NU_DOCU FROM TCDOCU_CLIE WHERE CO_EMPR = '02' AND NU_DOCU LIKE 'B028%') 
AND T1.CO_TIEN NOT IN (SELECT CO_TIEN FROM TMTIEN WHERE CO_EMPR='02' AND ST_PROY='S')
AND T1.FE_DOCU >= '2016/11/10'
AND T1.FE_DOCU <= '2016/11/10'
AND T1.TI_DOCU NOT IN ((SELECT TI_DOCU_ANTI FROM TMPARA_VENT WHERE CO_EMPR='02'),(SELECT TI_DOCU_NCRE FROM TMPARA_VENT WHERE CO_EMPR='02'),
						(SELECT TI_DOCU_NDEB FROM TMPARA_VENT WHERE CO_EMPR='02'))
AND T1.CO_ESTA_DOCU != 'ANU'

GROUP BY T1.NU_DOCU

ORDER BY 2,1,3,4